### ISSUE TITLE
Tokens not recognized because of ControlCharacter

### ISSUE THREAD

**Issue by SiNeumann** [dzieje-khorinis/DaedalusCompiler#58]
I first thank you for your work, I really appreciate the effort you put into this.
I use it in VSCode as built for my Gothic 2 Sources and it works great.
I encounterd a minor issue. ControlCharacters may lead to Token recognition errors.
I got into this when I freshly setup my PC. So the compiler should run without error against the "original" Gothic 2 sources. But I got an error. In DIA_VLK_439_Vatras.d line 566 unrecognized token. Well it turns out for whatever reason in the sources there is a FF (FormFeed) at position 1, after deleting the compiler ran without errors. I changed my VSCode settings to make CC visible. Anyway maybe you want to ignore these CCs.

Best regards

**Comment by Kisioj** [comment]
I just checked if other languages implementations ignore this character and it turns out they do (tested on g++ compiler and Python interpreter), so we also will do it. I just wonder if we should ignore all of control characters or just some of them. I guess I will check how it behaves in g++ or javac and make it work the same.

PS. New compiler release is going to be out in about a month, so be sure to check it out (much has been redone and fixed, extended syntax and full semantic errors support [or almost] will be included)

**Comment by Kirides** [comment]
Are there any benchmarks of the refactored compilers performance?

for my vs-code extension i used a modified version of the current version to accomplish ~3-4 seconds of compile time (for 1751 scripts) - though i am missing a lot of diagnostics.

i would need to be able to get all global and by function grouped-scoped symbol declarations, their types, aswell as meta information. This would have to be as fast as possible. (starting up the vs-code and and waiting for 30 seconds just is not developer friendly)  

e.g. 
- `const int myConst = 152;`
    - is `const`
    - of type `int`
    - with symbol name `myConst`
    - and constant value of `152`
- `var int myVar;`
    - is `var`
    - of type `int`
    - with symbol name `myVar`

**Comment by Kisioj** [comment]
@Kirides .DATs generation of all G2NK scripts on my computer takes below 10 seconds, which is already faster than original compiler (on my computer). Once planned features will be added, I will work on optimizations.

**Comment by Kisioj** [comment]
After thinking about it little more, I decided not to ignore control characters, since there is no reason why anybody would add them to the code.
